### PR TITLE
Use side margin on body

### PR DESCRIPTION
**Pull request by Seb33300**
This will allow to use `width: 100%` on body children without overflow

### CODE REVIEW

**Comment by mladenplavsic** [comment]
Hi, thanks for your contribution!

Could you please post an issue which will be solved with this change? It would be very helpful if there is a demo of the issue (fork this plunker https://plnkr.co/edit/E0ACEv?p=preview).

Cheers!

**Comment by Seb33300** [comment]
How should I do that? I never used it.

**Comment by Seb33300** [comment]
Ok, I think I managed to build it by installing nodejs, gulp & bower.
This should be ok now.

**Comment by mladenplavsic** [comment]
Fixes #3

**Pull request merged**
